# Generated by Django 4.2.7 on 2023-11-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0002_alter_authors_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.TextField(blank=True, null=True, verbose_name='Соединение'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='coord_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perevalapp.coords', verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevalapp.level', verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая информация'), ('ACCEPTED', 'Информация принята'), ('PENDING', 'В процессе'), ('REJECTED', 'Информация отклонена')], default='NEW', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevalapp.authors', verbose_name='Автор'),
        ),
    ]
