# Generated by Django 4.2.7 on 2023-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0003_alter_pereval_connect_alter_pereval_coord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативное название горы'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название горы'),
        ),
    ]
