# Generated by Django 4.2.7 on 2023-11-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0004_alter_pereval_other_titles_alter_pereval_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='beauty_title',
            field=models.CharField(default=None, max_length=255, verbose_name='Вид объекта'),
        ),
    ]
