# Generated by Django 4.2.7 on 2023-11-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0005_alter_pereval_beauty_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='user_email',
            field=models.CharField(default='', max_length=50, verbose_name='Почта'),
        ),
    ]
